# Estágio de Compilação
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copia arquivos de dependência
COPY go.mod ./
RUN go mod download

# Copia todo o código-fonte do backend
COPY . .

# Compila o binário estático do Auth Server
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o auth cmd/auth/main.go

# Estágio de Execução Mínimo
FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/auth .

# Expondo a porta HTTP do Auth Server
EXPOSE 8081

CMD ["./auth"]
