# Estágio de Compilação
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copia arquivos de dependência
COPY go.mod ./
RUN go mod download

# Copia todo o código-fonte do backend
COPY . .

# Compila o binário estático do World Server
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o world cmd/world/main.go

# Estágio de Execução Mínimo
FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/world .

# Expondo a porta HTTP do World Server
EXPOSE 8082

CMD ["./world"]
